// Generated by CoffeeScript 1.10.0
(function() {
  var alp, col, colors, fs, func, genFunc, genLinesColor, genPiePartColor, genPointColor, genPreviewDivColor, i, j, k, len, len1;

  fs = require('fs');

  colors = ["#5baaff", "#ff5c4f", "#a5e56e", "#ff8426", "#27ae60", "#34495e", "#2C82C9", "#EEE657", "#E01931", "#71BA51", "#b85c1f"];

  alp = "-abcdefghijklmnopqrstuvwxyz";

  genPreviewDivColor = function(col, i) {
    return ".color-" + i + " {background-color : " + col + ";}";
  };

  genLinesColor = function(col, i) {
    return ".ct-series-" + alp[i] + " .ct-line {stroke: " + col + "; stroke-width:4 ;}";
  };

  genPointColor = function(col, i) {
    return ".ct-series-" + alp[i] + " .ct-point {stroke: " + col + ";}";
  };

  genPiePartColor = function(col, i) {
    return ".ct-series-" + alp[i] + " .ct-slice-pie {fill: " + col + ";}";
  };

  genFunc = [genPreviewDivColor, genLinesColor, genPointColor, genPiePartColor];

  for (j = 0, len = genFunc.length; j < len; j++) {
    func = genFunc[j];
    for (i = k = 0, len1 = colors.length; k < len1; i = ++k) {
      col = colors[i];
      fs.appendFileSync("colors-stats.css", func(col, i + 1));
    }
  }

}).call(this);
